name: Setup repo

description: Setup repo with all features on CI

inputs:
  python-version:
    description: "Python version"
    required: true
    default: "3.10"
  architecture:
    description: "Which architecture to run on"
    required: true
    default: x64

runs:
  using: composite
  steps:
    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: ${{ inputs.python-version }}
        architecture: ${{ inputs.architecture }}
    - name: Get pip cache dir
      id: pip-cache
      shell: bash
      run: echo "directory=$(pip cache dir)" >> $GITHUB_OUTPUT
    - uses: bazelbuild/setup-bazelisk@v2
    - name: Get cache key prefix
      id: get-cache-key-prefix
      shell: bash
      run: |
        echo "prefix=$ImageOS-$ImageVersion" >> $GITHUB_OUTPUT
    - name: PyPI cache
      id: pypi-cache
      uses: actions/cache@v3.0.10
      with:
        key: ${{ steps.get-cache-key-prefix.outputs.prefix }}-pypi
        path: ${{ steps.pip-cache.outputs.directory }}
        restore-keys: |
          ${{ steps.get-cache-key-prefix.outputs.prefix }}-pypi-
    - name: Bazel cache
      id: bazel-cache
      uses: actions/cache@v3.0.10
      with:
        key: ${{ steps.get-cache-key-prefix.outputs.prefix }}-bazel
        path: |
          ~/.cache/bazel
          tools/
        restore-keys: |
          ${{ steps.get-cache-key-prefix.outputs.prefix }}-bazel-
    - name: Install development dependencies
      shell: bash
      run: |
        bazel run //requirements:pypi.update
        python -m pip install -r requirements/pypi.txt
    - name: Setup node
      uses: actions/setup-node@v3
      with:
        node-version: "17"
    - name: Install pyright
      shell: bash
      run: npm install -g npm@^7 pyright

