package(default_visibility = ["//visibility:__pkg__"])

# sets of *-requirements.in files to then be used by compile_pip_requirements
exports_files(glob(["*-requirements.in"]))
exports_files(glob(["*-requirements.lock.txt"]))
