#!/usr/bin/env bash

GIT_ROOT=$(git rev-parse --show-toplevel)

cd "${GIT_ROOT}" || exit 1

arr=("38" "39" "310" "311")

for name in "${arr[@]}"; do
    bazel run "//requirements:pypi_${name}.update"
done
