load("@bazel_skylib//:bzl_library.bzl", "bzl_library")

package(default_visibility = ["//:__subpackages__"])

exports_files(["deps.bzl"])

bzl_library(
    name = "python.bzl",
    srcs = ["python.bzl"],
)
